### ISSUE TITLE
在win10的powershell中用python3.7时，会报错File "C:\Users\MrL\Anaconda3\lib\site-packages\pretty_errors\__init__.py", line 495, in write_code     lines.append(line.rstrip()) AttributeError: 'int' object has no attribute 'rstrip'

### ISSUE THREAD

**Issue by Rindrop** [onelivesleft/PrettyErrors#18]
在win10的powershell中用python3.7时，会报错如下：

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\MrL\Anaconda3\lib\site-packages\pretty_errors\__init__.py", line 679, in excepthook
    code_string = writer.write_code(code.co_filename, traceback.tb_lineno, frame.f_globals, count == final)
  File "C:\Users\MrL\Anaconda3\lib\site-packages\pretty_errors\__init__.py", line 495, in write_code
    lines.append(line.rstrip())
AttributeError: 'int' object has no attribute 'rstrip'
```

将lines.append(line.rstrip())替换成lines.append(str(line).rstrip())之后，使用正常

**Comment by Rindrop** [comment]
当我在vscode中使用的时候，因新的更改出现了新的bug：
`
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\MrL\Anaconda3\lib\site-packages\pretty_errors\__init__.py", line 680, in excepthook
    code_string = writer.write_code(code.co_filename, traceback.tb_lineno, frame.f_globals, count == final)
  File "C:\Users\MrL\Anaconda3\lib\site-packages\pretty_errors\__init__.py", line 501, in write_code
    start = line - self.config.lines_before
TypeError: unsupported operand type(s) for -: 'str' and 'int'
`
最好的解决办法还是应该在lines.append(str(line).rstrip())语句中转换。

**Comment by onelivesleft** [comment]
Updated to v1.2.15 which should fix it.
