### ISSUE TITLE
line_length default of 0 causes division by zero exception unless overridden

### ISSUE THREAD

**Issue by westhomas** [onelivesleft/PrettyErrors#41]
I'm not sure why `line_length` isn't being changed from it's default of 0, but it's not in my aiohttp/docker container setup. 

If I pass `line_length=79` into configure, the exception goes away.

Maybe 0 isn't a good default? Or the modulo needs better protection.

```
handlers.py 236 middleware_handler2021-08-19T16:49:59.121Z ERROR MainProcess:MainThread aiohttp.server:355 Error handling request
Traceback (most recent call last):
  File "/app/server/handlers.py", line 236, in middleware_handler
    response = await handler(request)
  File "/app/server/handlers.py", line 419, in list_patient_workers
    raise Exception("oops. There was a problem.")
Exception: oops. There was a problem.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/app/server/handlers.py", line 264, in middleware_handler
    pretty_errors.excepthook(*sys.exc_info())
  File "/usr/local/lib/python3.6/site-packages/pretty_errors/__init__.py", line 738, in excepthook
    writer.write_location(code.co_filename, traceback.tb_lineno, code.co_name)
  File "/usr/local/lib/python3.6/site-packages/pretty_errors/__init__.py", line 491, in write_location
    self.config.function_color,    function
  File "/usr/local/lib/python3.6/site-packages/pretty_errors/__init__.py", line 428, in output_text
    if count == 0 or count % line_length != 0 or self.config.full_line_newline:
ZeroDivisionError: integer division or modulo by zero

```

**Comment by onelivesleft** [comment]
I'm surmising that your container is reporting a terminal width of 0; I've guarded against that, so it should now be working even if you leave `line_length` at zero.
